name: distr_inf
channels:
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - python=3.6 # Version 3.9 also works
  - torchvision # Version 0.11.3
  - flake8 # Version 4.0.1
  - torchaudio # Version 0.10.2
  - cudatoolkit=11.1
  - pytorch # Version 1.10.2
  - robustness # Any version should be okay