#!/bin/bash

python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.5/split_1/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_1/male_0.5/casia/1/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.5/split_1/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_1/male_0.5/casia/2/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.5/split_1/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_1/male_0.5/casia/3/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.5/split_2/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_2/male_0.5/casia/1/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.5/split_2/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_2/male_0.5/casia/2/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.5/split_2/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_2/male_0.5/casia/3/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.3/split_1/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_1/male_0.3/casia/1/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.3/split_1/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_1/male_0.3/casia/2/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.3/split_1/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_1/male_0.3/casia/3/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.3/split_2/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_2/male_0.3/casia/1/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.3/split_2/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_2/male_0.3/casia/2/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.3/split_2/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_2/male_0.3/casia/3/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.7/split_1/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_1/male_0.7/casia/1/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.7/split_1/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_1/male_0.7/casia/2/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.7/split_1/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_1/male_0.7/casia/3/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.7/split_2/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_2/male_0.7/casia/1/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.7/split_2/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_2/male_0.7/casia/2/ --weightinit casia-webface
python permutation_numbers.py --dataset celeba --bs 768 --which /p/adversarialml/as9rw/datasets/celeba_raw_crop/splits/50_50/male_0.7/split_2/ --savepath /p/adversarialml/as9rw/celeb_models/50_50/split_2/male_0.7/casia/3/ --weightinit casia-webface